### ISSUE TITLE
PasswordGrantProvider can not use

### ISSUE THREAD

**Issue by reoxu** [ocadotechnology/sttp-oauth2#335]
we use
<dependency>
    <groupId>com.ocadotechnology</groupId>
    <artifactId>sttp-oauth2_2.12</artifactId>
    <version>0.15.2</version>
</dependency>
got this err
![image](https://user-images.githubusercontent.com/114573733/211299860-4ef5db38-c2f5-4236-8853-1352212cef87.png)
How can we use PasswordGrantProvider in right way.

**Comment by jsienniak** [comment]
Hi @reoxu,

If you look at signature of `PasswordGrantProvider`:
```
def apply[F[_]: MonadThrow](
    tokenUrl: Uri,
    clientId: NonEmptyString,
    clientSecret: Secret[String]
  )(
    backend: SttpBackend[F, Any]
  ): PasswordGrantProvider[F]
  ```
  
  You need to use an effect (F), for which you have and instance of both `SttpBackend` and ` MonadThrow`, for example cats's `IO`.  If you would share a type of your `backend` value I could help you more.

**Comment by bwiercinski** [comment]
it have to be one of [synchronous backend](https://sttp.softwaremill.com/en/latest/backends/synchronous.html), as compiler is looking for `cats.MonadThrow[Identity]`. imo the library should input use `sttp.model.MonadError` not cats' MonadThrow. i've made similar migration in ac508e486597fdafea6e6a433db36d0516c2c1e0 commit

**Comment by majk-p** [comment]
Changes from @bwiercinski have been introduced in https://github.com/ocadotechnology/sttp-oauth2/releases/tag/v0.16.0

@reoxu please update the version, it should help with your issue

**Comment by reoxu** [comment]
> Changes from @bwiercinski have been introduced in https://github.com/ocadotechnology/sttp-oauth2/releases/tag/v0.16.0
> 
> @reoxu please update the version, it should help with your issue

Hi @majk-p, I download the v0.16.0 source code and try to build it, but failed.

**Comment by reoxu** [comment]
> Changes from @bwiercinski have been introduced in https://github.com/ocadotechnology/sttp-oauth2/releases/tag/v0.16.0
> 
> @reoxu please update the version, it should help with your issue

Hi @majk-p, i download v0.16.0 source and try to build it, but failed.
![image](https://user-images.githubusercontent.com/114573733/211469264-b88fecfd-037e-4623-8b18-12bb4227060a.png)
I fix code 
mdocVariables := Map(
      "VERSION" -> "0.16.0"
      // "VERSION" -> { if (isSnapshot.value) previousStableVersion.value.get else version.value }
)
got jar file name like this sttp-oauth2_2.12-HEAD+20230110-1326.jar

**Comment by reoxu** [comment]
I use sttp-oauth2_2.12-HEAD+20230110-1326.jar, got this err.
![image](https://user-images.githubusercontent.com/114573733/211477867-17fc39cf-396f-410a-8e00-7dbc213ddd62.png)

**Comment by bwiercinski** [comment]
@reoxu can you paste whole stacktrace?

**Comment by reoxu** [comment]
> @reoxu can you paste whole stacktrace?

Exception in thread "main" com.ocadotechnology.sttp.oauth2.common$OAuth2Exception: Client call resulted in error (200): Missing required field: DownField(user_name)
	at com.ocadotechnology.sttp.oauth2.PasswordGrantProvider$.$anonfun$apply$5(PasswordGrantProvider.scala:30)
	at cats.syntax.EitherOps$.leftMap$extension(either.scala:193)
	at com.ocadotechnology.sttp.oauth2.PasswordGrantProvider$.$anonfun$apply$4(PasswordGrantProvider.scala:30)
	at sttp.client3.monad.IdMonad$.map(IdMonad.scala:8)
	at sttp.monad.syntax$MonadErrorOps.map(MonadError.scala:60)
	at com.ocadotechnology.sttp.oauth2.PasswordGrantProvider$.$anonfun$apply$2(PasswordGrantProvider.scala:30)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:61)
	at com.ocadotechnology.sttp.oauth2.PasswordGrantProvider$.$anonfun$apply$1(PasswordGrantProvider.scala:31)
	at OauthTest$.main(OauthTest.scala:18)
	at OauthTest.main(OauthTest.scala)
Caused by: com.ocadotechnology.sttp.oauth2.common$Error$HttpClientError: Client call resulted in error (200): Missing required field: DownField(user_name)
	at com.ocadotechnology.sttp.oauth2.common$.$anonfun$responseWithCommonError$1(common.scala:103)
	at sttp.client3.MappedResponseAs.$anonfun$mapWithMetadata$1(ResponseAs.scala:91)
	at sttp.client3.internal.BodyFromResponseAs.$anonfun$doApply$2(BodyFromResponseAs.scala:24)
	at sttp.client3.monad.IdMonad$.map(IdMonad.scala:8)
	at sttp.monad.syntax$MonadErrorOps.map(MonadError.scala:60)
	at sttp.client3.internal.BodyFromResponseAs.doApply(BodyFromResponseAs.scala:24)
	at sttp.client3.internal.BodyFromResponseAs.$anonfun$apply$1(BodyFromResponseAs.scala:14)
	at sttp.monad.syntax$MonadErrorOps.map(MonadError.scala:60)
	at sttp.client3.internal.BodyFromResponseAs.apply(BodyFromResponseAs.scala:14)
	at sttp.client3.HttpURLConnectionBackend.readResponse(HttpURLConnectionBackend.scala:245)
	at sttp.client3.HttpURLConnectionBackend.$anonfun$send$1(HttpURLConnectionBackend.scala:56)
	at scala.util.Try$.apply(Try.scala:209)
	at sttp.monad.MonadError.handleError(MonadError.scala:24)
	at sttp.monad.MonadError.handleError$(MonadError.scala:23)
	at sttp.client3.monad.IdMonad$.handleError(IdMonad.scala:6)
	at sttp.client3.SttpClientException$.adjustExceptions(SttpClientException.scala:58)
	at sttp.client3.HttpURLConnectionBackend.adjustExceptions(HttpURLConnectionBackend.scala:295)
	at sttp.client3.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:30)
	at sttp.client3.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:22)
	at sttp.client3.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:29)
	at sttp.client3.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:24)
	at com.ocadotechnology.sttp.oauth2.PasswordGrant$.$anonfun$requestToken$1(PasswordGrant.scala:40)
	at sttp.monad.syntax$MonadErrorOps.map(MonadError.scala:60)
	at com.ocadotechnology.sttp.oauth2.PasswordGrant$.requestToken(PasswordGrant.scala:42)
	at com.ocadotechnology.sttp.oauth2.PasswordGrantProvider$.$anonfun$apply$3(PasswordGrantProvider.scala:29)
	... 6 more
Caused by: sttp.client3.DeserializationException: Missing required field: DownField(user_name)
	at sttp.client3.ResponseAs$.$anonfun$deserializeWithError$1(ResponseAs.scala:201)
	at sttp.client3.ResponseAs$.$anonfun$deserializeRightWithError$1(ResponseAs.scala:180)
	at sttp.client3.MappedResponseAs.$anonfun$mapWithMetadata$1(ResponseAs.scala:91)
	... 30 more

Process finished with exit code 1

**Comment by bwiercinski** [comment]
i've made an new issue since it is not related with this one. pls use https://github.com/ocadotechnology/sttp-oauth2/issues/337. in my opinion this issue is solved and we are waiting with closing until the version is properly released.
